global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: ratelimiter
    static_configs:
      - targets: ["app:9090"]
  - job_name: redis
    static_configs:
      - targets: ["redis-exporter:9121"]
